apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --out k8s/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: auth-service
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: auth-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --out k8s/
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: auth-service
    spec:
      containers:
        - env:
            - name: JAVA_TOOL_OPTIONS
              value: -javaagent:/otel/opentelemetry-javaagent.jar
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://lgtm:4318
            - name: OTEL_LOGS_EXPORTER
              value: otlp
            - name: OTEL_METRICS_EXPORTER
              value: otlp
            - name: OTEL_TRACES_EXPORTER
              value: otlp
            - name: SPRING_DATASOURCE_PASSWORD
              value: auth_pass
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-auth:5432/auth_db
            - name: SPRING_DATASOURCE_USERNAME
              value: auth_user
            - name: SPRING_DATASOURCE_DRIVER-CLASS-NAME
              value: org.postgresql.Driver
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
              value: org.hibernate.dialect.PostgreSQLDialect
          image: chaditaqi/auth-service:latest
          imagePullPolicy: Always
          name: auth-service
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /app/.env
              name: auth-service-cm0
              readOnly: true
              subPath: .env
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: .env
                path: .env
            name: auth-service-cm0
          name: auth-service-cm0
