apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --out k8s/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: entreprise
  name: entreprise
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: entreprise
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --out k8s/
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: entreprise
    spec:
      containers:
        - env:
            - name: JAVA_TOOL_OPTIONS
              value: -javaagent:/otel/opentelemetry-javaagent.jar
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://lgtm:4318
            - name: OTEL_LOGS_EXPORTER
              value: otlp
            - name: OTEL_METRICS_EXPORTER
              value: otlp
            - name: OTEL_TRACES_EXPORTER
              value: otlp
            - name: SPRING_DATASOURCE_PASSWORD
              value: entreprise_pass
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-entreprise:5432/entreprise_db
            - name: SPRING_DATASOURCE_USERNAME
              value: entreprise_user
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: org.postgresql.Driver
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
              value: org.hibernate.dialect.PostgreSQLDialect
          image: backup_devops_project-entreprise:latest
          imagePullPolicy: Never
          name: entreprise
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
