apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --out k8s/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gateway
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --out k8s/
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: gateway
    spec:
      containers:
        - env:
            - name: JAVA_TOOL_OPTIONS
              value: -javaagent:/otel/opentelemetry-javaagent.jar
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://lgtm:4318
            - name: OTEL_LOGS_EXPORTER
              value: otlp
            - name: OTEL_METRICS_EXPORTER
              value: otlp
            - name: OTEL_TRACES_EXPORTER
              value: otlp
          image: chaditaqi/gateway:latest
          imagePullPolicy: Always
          name: gateway
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
