apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert --out k8s/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: kafka
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert --out k8s/
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: kafka
    spec:
      initContainers:
      - name: wait-for-zookeeper
        image: busybox:1.35
        command:
        - sh
        - -c
        - "echo \"Waiting for Zookeeper to be ready...\"\nuntil nc -z zookeeper 2181;\
          \ do\n  echo \"Zookeeper not ready, waiting...\"\n  sleep 5\ndone\necho\
          \ \"Zookeeper is ready!\"\n"
      containers:
      - env:
        - name: KAFKA_ADVERTISED_LISTENERS
          value: ''
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: 'true'
        - name: KAFKA_BROKER_ID
          value: '1'
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://0.0.0.0:9092
        - name: KAFKA_LOG_DIRS
          value: /var/lib/kafka/data
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: '1'
        - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
          value: '1'
        - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: '1'
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        - name: KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS
          value: '18000'
        - name: KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS
          value: '18000'
        - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
          value: '0'
        - name: KAFKA_LOG_RETENTION_HOURS
          value: '168'
        - name: KAFKA_LOG_SEGMENT_BYTES
          value: '1073741824'
        - name: KAFKA_LOG_RETENTION_BYTES
          value: '1073741824'
        - name: KAFKA_PORT
          value: ''
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: confluentinc/cp-kafka:7.4.0
        name: kafka
        ports:
        - containerPort: 9092
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - kafka-broker-api-versions --bootstrap-server localhost:9092
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        resources:
          requests:
            memory: 1Gi
            cpu: 500m
          limits:
            memory: 2Gi
            cpu: 1000m
        volumeMounts:
        - mountPath: /var/lib/kafka/data
          name: kafka-data
        command:
        - sh
        - -c
        args:
        - 'export KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://$POD_IP:9092

          exec /etc/confluent/docker/run'
      restartPolicy: Always
      volumes:
      - name: kafka-data
        persistentVolumeClaim:
          claimName: kafka-data
