apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --out k8s/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: mission-service
  name: mission-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mission-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --out k8s/
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: mission-service
    spec:
      containers:
        - env:
            - name: JAVA_TOOL_OPTIONS
              value: -javaagent:/otel/opentelemetry-javaagent.jar
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://lgtm:4318
            - name: OTEL_LOGS_EXPORTER
              value: otlp
            - name: OTEL_METRICS_EXPORTER
              value: otlp
            - name: OTEL_TRACES_EXPORTER
              value: otlp
            - name: SPRING_DATASOURCE_PASSWORD
              value: mission_pass
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-mission:5432/mission_db
            - name: SPRING_DATASOURCE_USERNAME
              value: mission_user
          image: backup_devops_project-mission-service:latest
          imagePullPolicy: Never
          name: mission-service
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
