# k8s/postgres-telemetry-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: postgres-telemetry
  labels:
    io.kompose.service: postgres-telemetry
spec:
  type: ClusterIP
  selector:
    io.kompose.service: postgres-telemetry
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
