apiVersion: v1
kind: Service
metadata:
  name: postgres-auth
  labels:
    io.kompose.service: postgres-auth
spec:
  type: ClusterIP
  selector:
    io.kompose.service: postgres-auth
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
