# k8s/postgres-spacecraft-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: postgres-spacecraft
  labels:
    io.kompose.service: postgres-spacecraft
spec:
  type: ClusterIP
  selector:
    io.kompose.service: postgres-spacecraft
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432