apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --out k8s/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: postgres-spacecraft
  name: postgres-spacecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres-spacecraft
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --out k8s/
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: postgres-spacecraft
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: spacecraft_db
            - name: POSTGRES_PASSWORD
              value: spacecraft_pass
            - name: POSTGRES_USER
              value: spacecraft_user
          image: postgres:17
          name: postgres-spacecraft
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: spacecraft-data
      restartPolicy: Always
      volumes:
        - name: spacecraft-data
          persistentVolumeClaim:
            claimName: spacecraft-data
