apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --out k8s/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: postgres-entreprise
  name: postgres-entreprise
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres-entreprise
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --out k8s/
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: postgres-entreprise
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: entreprise_db
            - name: POSTGRES_PASSWORD
              value: entreprise_pass
            - name: POSTGRES_USER
              value: entreprise_user
          image: postgres:17
          name: postgres-entreprise
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: entreprise-data
      restartPolicy: Always
      volumes:
        - name: entreprise-data
          persistentVolumeClaim:
            claimName: entreprise-data
