apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --out k8s/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: postgres-telemetry
  name: postgres-telemetry
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres-telemetry
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --out k8s/
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: postgres-telemetry
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: telemetry_db
            - name: POSTGRES_PASSWORD
              value: telemetry_pass
            - name: POSTGRES_USER
              value: telemetry_user
          image: timescale/timescaledb:latest-pg17
          name: postgres-telemetry
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: telemetry-data
      restartPolicy: Always
      volumes:
        - name: telemetry-data
          persistentVolumeClaim:
            claimName: telemetry-data
