# k8s/postgres-mission-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: postgres-mission
  labels:
    io.kompose.service: postgres-mission
spec:
  type: ClusterIP
  selector:
    io.kompose.service: postgres-mission
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432

