version: "3.8"

services:
  db:
    image: postgres:17.4
    container_name: spacecraft-postgres
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: spacecraft_db
      POSTGRES_USER: spacecraft_user
      POSTGRES_PASSWORD: spacecraft_pass
    volumes:
      - spacecraft_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U spacecraft_user"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  spacecraft_data:
