# 1) build stage
FROM node:18-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install --legacy-peer-deps
COPY . .
RUN npm run build        

# 2) run stage
FROM node:18-alpine
WORKDIR /app
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next   ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./
COPY .env.local ./

# Add environment variable to trust localhost
ENV AUTH_TRUST_HOST=true

EXPOSE 3000
CMD ["npm", "run", "start"]  
