name: telemetry
server:
  port: 8080

spring:
  application:
    name: telemetry-service

  datasource:
    url: jdbc:postgresql://postgres-telemetry:5432/telemetry_db
    username: telemetry_user
    password: telemetry_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: kafka:9092

    consumer:
      group-id: telemetry-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: true
      max-poll-interval-ms: 300000
      session-timeout-ms: 45000
      heartbeat-interval-ms: 10000

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

spacecraft:
  url: http://spacecraft:8080

n2yo:
  api:
    base-url: https://api.n2yo.com/rest/v1
    key: "2Q9ZTN-2WB26E-FBNTLF-5FTW"
